options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/cnas-assignment-467305/php-repo/cnas-php-app:$SHORT_SHA', '.']

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/cnas-assignment-467305/php-repo/cnas-php-app:$SHORT_SHA']

  # Step 3: Configure kubectl to connect to GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cnas-cluster'
      - '--region=asia-southeast1'
      - '--project=cnas-assignment-467305'

  # Step 4: Apply all Kubernetes manifests (create/update resources)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cnas-cluster'

  # Step 5: Update Deployment with latest image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/cnas-php-app'
      - 'php=asia-southeast1-docker.pkg.dev/cnas-assignment-467305/php-repo/cnas-php-app:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cnas'

