CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100)
);

CREATE USER 'prometheus'@'%' IDENTIFIED BY 'password';
GRANT SELECT, PROCESS, SHOW DATABASES, SHOW VIEW ON *.* TO 'prometheus'@'%';
FLUSH PRIVILEGES;
